name: Java CI     #Actions名称

on:
  push:
    branches:
      - master       #在提交master时触发
jobs:
  build:
    runs-on: ubuntu-latest    #运行环境

    steps:
    - uses: actions/checkout@master    #获取master分支
      with:
        ref: master  # 切换到master分支
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1  #使用官方脚本创建java环境
      with:
        java-version: 1.8

#    - name: Set SSH Environment
#      run: |
#        mkdir -p ~/.ssh/
#        echo "${{ secrets.ID_RSA }}" > ~/.ssh/id_rsa
#        echo "${{ secrets.ID_RSA_PUB }}" > ~/.ssh/id_rsa.pub
#        cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
#        chmod 600 ~/.ssh/id_rsa
#        chmod 700 ~/.ssh && chmod 700 ~/.ssh/*
#        ls -l ~/.ssh/
#
#    - name: Download config file and replace
#      run: |
#        git clone git@github.com:beidou777/dipper-blog-config.git
#        mv -f ./mogu_prod_configuration/dev_config/mogu_admin/application.yml ./mogu_admin/src/main/resources/application.yml
#        mv -f ./mogu_prod_configuration/dev_config/mogu_eureka/application.yml ./mogu_eureka/src/main/resources/application.yml
#        mv -f ./mogu_prod_configuration/dev_config/mogu_picture/application.yml ./mogu_picture/src/main/resources/application.yml
#        mv -f ./mogu_prod_configuration/dev_config/mogu_sms/application.yml ./mogu_sms/src/main/resources/application.yml
#        mv -f ./mogu_prod_configuration/dev_config/mogu_web/application.yml ./mogu_web/src/main/resources/application.yml
#        mv -f ./mogu_prod_configuration/dev_config/vue_mogu_admin/config.js ./vue_mogu_admin/static/ckeditor/config.js
#        mv -f ./mogu_prod_configuration/dev_config/vue_mogu_admin/prod.env.js ./vue_mogu_admin/config/prod.env.js
#        mv -f ./mogu_prod_configuration/dev_config/vue_mogu_web/prod.env.js ./vue_mogu_web/config/prod.env.js

    - name: Build Java jar
      run: |
        mvn clean install

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Build vue_mogu_admin and vue_mogu_web
      run: |
        cd ./vue_mogu_admin
        npm install
        npm run build
        cd ..
        cd ./vue_mogu_web
        npm install
        npm run build
        cd ..

        # 构建镜像，指定镜像名
        - name: Build Java Docker Images
          run: |
            echo '=====开始构建镜像====='
            echo '=====开始构建mogu_admin====='
            cd mogu_admin
            mvn docker:build
            cd ..
            echo '=====开始构建mogu_gateway====='
            cd mogu_gateway
            mvn docker:build
            cd ..
            echo '=====开始构建mogu_monitor====='
            cd mogu_monitor
            mvn docker:build
            cd ..
            echo '=====开始构建mogu_picture====='
            cd mogu_picture
            mvn docker:build
            cd ..
            echo '=====开始构建mogu_search====='
            cd mogu_search
            mvn docker:build
            cd ..
            echo '=====开始构建mogu_sms====='
            cd mogu_sms
            mvn docker:build
            cd ..
            echo '=====开始构建mogu_spider====='
            cd mogu_spider
            mvn docker:build
            cd ..
            echo '=====开始构建mogu_web====='
            cd mogu_web
            mvn docker:build
            cd ..
            echo '=====镜像构建结束====='
        # 构建镜像，指定镜像名
        - name: Build Vue Docker Images
          run: |
            echo '=====开始构建镜像====='
            echo '=====开始构建vue_mogu_admin====='
            cd vue_mogu_admin
            docker build -t registry.cn-shenzhen.aliyuncs.com/dipper-blog/vue_mogu_admin .
            cd ..
            cd vue_mogu_web
            docker build -t registry.cn-shenzhen.aliyuncs.com/dipper-blog/vue_mogu_web .
            cd ..
            echo '=====镜像构建结束====='
        # 登录到 阿里云镜像服务，使用 GitHub secrets 传入账号密码，密码被加密存储在 GitHub 服务器
        - name: Login to Aliyun
          uses: docker/login-action@v1
          with:
            registry: registry.cn-shenzhen.aliyuncs.com
            username: ${{ secrets.ALIYUN_USER_NAME }}
            password: ${{ secrets.ALIYUN_PASSWORD }}

        - name: Push Docker Image
          run: |
            echo '=====开始上传镜像====='
            echo '=====开始上传mogu_admin====='
            docker push registry.cn-shenzhen.aliyuncs.com/dipper-blog/mogu_admin
            echo '=====开始上传mogu_gateway====='
            docker push registry.cn-shenzhen.aliyuncs.com/dipper-blog/mogu_gateway
            echo '=====开始上传mogu_monitor====='
            docker push registry.cn-shenzhen.aliyuncs.com/dipper-blog/mogu_monitor
            echo '=====开始上传mogu_picture====='
            docker push registry.cn-shenzhen.aliyuncs.com/dipper-blog/mogu_picture
            echo '=====开始上传mogu_search====='
            docker push registry.cn-shenzhen.aliyuncs.com/dipper-blog/mogu_search
            echo '=====开始上传mogu_sms====='
            docker push registry.cn-shenzhen.aliyuncs.com/dipper-blog/mogu_sms
            echo '=====开始上传mogu_spider====='
            docker push registry.cn-shenzhen.aliyuncs.com/dipper-blog/mogu_spider
            echo '=====开始上传mogu_web====='
            docker push registry.cn-shenzhen.aliyuncs.com/dipper-blog/mogu_web
            echo '=====开始上传vue_mogu_admin====='
            docker push registry.cn-shenzhen.aliyuncs.com/dipper-blog/vue_mogu_admin
            echo '=====开始上传vue_mogu_web====='
            docker push registry.cn-shenzhen.aliyuncs.com/dipper-blog/vue_mogu_web
            echo '=====镜像上传结束====='
#      - name: Update New Docker Image And Restart Server
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.DOCKER_IP_DEV_NACOS }}
#          username: ${{ secrets.DOCKER_ID }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#          port: 22
#          script: |
#            cd /root/docker-compose/bin
#            ./update.sh
